version: 2.19.11

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: chmod +x mnvw
      - run: 
          command: ./mvnw -Dmaven.test.skip=true package

        
